#ifndef BLB_CONFIG_H
#define BLB_CONFIG_H

#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>

#define BLB_PATH_MAX 256

extern bool BLB_DEBUG;

extern bool BLB_OBJECT_AGGREGATION;
extern int BLB_OBJECT_AGGREGATION_MIN_OBJECTS;
extern float BLB_OBJECT_AGGREGATION_MAX_DISTANCE;
extern bool BLB_OBJECT_AGGREGATION_REBUILD_ON_TRANSFORM_CHANGE;
extern bool BLB_OBJECT_AGGREGATION_STATIC_ONLY;
extern int BLB_OBJECT_AGGREGATION_MAX_CLUSTER_TRIANGLES;

extern bool BLB_OBJECT_SMART_OPTIMIZATION;
extern int BLB_OBJECT_OPTIMIZATION_STATIC_RECOVER_FRAMES;
extern float BLB_OBJECT_OPTIMIZATION_MOTION_POSITION_EPSILON;
extern float BLB_OBJECT_OPTIMIZATION_MOTION_ROTATION_EPSILON;

extern bool BLB_OBJECT_INSTANCING;
extern int BLB_OBJECT_INSTANCING_MIN_OBJECTS;
extern int BLB_OBJECT_INSTANCING_MAX_INSTANCES;
extern bool BLB_OBJECT_2D_INSTANCING;
extern int BLB_OBJECT_2D_INSTANCING_MIN_OBJECTS;
extern bool BLB_PARTICLE_INSTANCING;
extern int BLB_PARTICLE_INSTANCING_MAX_INSTANCES;
extern bool BLB_PARTICLE_CULLING;
extern int BLB_RENDER_ASYNC_WORKERS;

extern bool BLB_OBJECT_LOD;
extern int BLB_OBJECT_LOD_LEVELS;
extern float BLB_OBJECT_LOD_ERROR;
extern float BLB_OBJECT_LOD_REDUCTION;
extern float BLB_OBJECT_LOD_FALLBACK_ERROR;
extern int BLB_OBJECT_LOD_DEFAULT_LEVEL;
extern bool BLB_OBJECT_LOD_DISTANCE_OPTIMIZATION;
extern float BLB_OBJECT_LOD_DISTANCE_START;
extern float BLB_OBJECT_LOD_DISTANCE_STEP;
extern int BLB_OBJECT_LOD_MIN_LEVEL;
extern int BLB_OBJECT_LOD_MIN_TRIANGLES;
extern int BLB_OBJECT_LOD_SHADOW_MAX_LEVEL;
extern bool BLB_OBJECT_LOD_CACHE;
extern int BLB_OBJECT_LOD_CACHE_MAX_ENTRIES;
extern size_t BLB_OBJECT_LOD_CACHE_MAX_BYTES;
extern bool BLB_OBJECT_LOD_PRESERVE_BOUNDARIES;
extern bool BLB_OBJECT_LOD_PRESERVE_NORMALS;

extern bool BLB_OBJECT_VISIBILITY_CACHE;
extern int BLB_OBJECT_VISIBILITY_CACHE_MAX_ENTRIES;
extern int BLB_OBJECT_VISIBILITY_CACHE_MAX_AGE;
extern float BLB_OBJECT_VISIBILITY_CACHE_FAR_DISTANCE;
extern int BLB_OBJECT_VISIBILITY_CACHE_FAR_MAX_AGE;

extern bool BLB_OBJECT_CULLING;
extern bool BLB_OBJECT_FRUSTUM_CULLING;
extern bool BLB_OBJECT_DISTANCE_CULLING;
extern float BLB_OBJECT_MAX_RENDER_DISTANCE;
extern float BLB_OBJECT_CULLING_MARGIN;
extern bool BLB_OBJECT_SHADOW_CULL_BY_CAMERA;
extern float BLB_OBJECT_MAX_SHADOW_RENDER_DISTANCE;

extern bool BLB_HSA;
extern int BLB_HSA_LEVELS;
extern float BLB_HSA_ERROR;
extern float BLB_HSA_REDUCTION_FACTOR;
extern int BLB_HSA_MAX_TRIANGLES;

extern char BLB_DEFAULT_CACHE_PATH[BLB_PATH_MAX];

void BLB_InitConfig(void);

#endif
