set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(MINGW_TRIPLE x86_64-w64-mingw32)

set(CMAKE_C_COMPILER ${MINGW_TRIPLE}-gcc)
set(CMAKE_CXX_COMPILER ${MINGW_TRIPLE}-g++)
set(CMAKE_RC_COMPILER ${MINGW_TRIPLE}-windres)

set(CMAKE_FIND_ROOT_PATH
    /usr/${MINGW_TRIPLE}
)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(WINDOWS_VULKAN_ROOT
    "${CMAKE_SOURCE_DIR}/third_party/windows/vulkan"
)

set(Vulkan_INCLUDE_DIR
    "/usr/include"
    CACHE PATH "" FORCE
)

set(Vulkan_LIBRARY
    "${WINDOWS_VULKAN_ROOT}/libvulkan-1.dll.a"
    CACHE FILEPATH "" FORCE
)

set(GLFW3_DIR "${CMAKE_SOURCE_DIR}/third_party/windows/glfw/lib/cmake/glfw3" CACHE PATH "" FORCE)
